site_name: Cora Developer Guide
theme:
  name: material
  favicon: 'img/nprocessor-logos/logonobg.png'
  logo: 'img/nprocessor-logos/logo2nobg.png'
  font: false
  features:
    - instant
markdown_extensions:
  - markdown.extensions.footnotes
  - markdown.extensions.smarty
  - markdown.extensions.admonition
  - markdown.extensions.toc:
      permalink: True
  - markdown.extensions.tables
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - js/MathJax-2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
  - css/fonts.css
  - css/style.css
plugins:
  - markdownextradata
  - search
nav:
- 'Home': 'index.md'
- Getting Started:
  - "Beginner's Guide(must read)": 'getting-started/beginner-guide(must read).md'
  - "Analysis of Berkeley Hardfloat": 'getting-started/analysis-of-berkeley-hardfloat.md'
  - "Applying Berkeley Hardfloat": 'getting-started/applying-berkeley-hardfloat.md'
  - "Applying ofdm cordic(need to be tested)": 'getting-started/applying-ofdm-cordic(need to be tested).md'
  - "Retiming Guide": 'getting-started/retiming-guide.md'
- Cora Front-end:
  - "Overview": 'cora-front-end/overview.md'
- Register Table for CSB:
  - "Register Table": 'register-table-for-csb/register-table-for-csb.md'
- Firesim/FPGA:
  - "firesim": 'firesim/nprocessor-firesim-account.md'
- About:
    - 'License': 'about/license.md'
copyright: If you wish to improve this site, please <a href="https://github.com/coraproject/cora-docs">open an issue</a> or <a href="https://github.com/coraproject/cora-docs/compare">send a pull request</a>.<br>coradocs v0.0.0. Cora Project 2020.
